site_name: 1minPython
theme:
  name: material
  language: zh
  # features:
  #     - tabs
  # font:
  #   text: Ubuntu
  #   code: Ubuntu Mono
markdown_extensions:
  - footnotes
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

  # google_analytics:
  # - UA-XXXXXXXX-X
  # - auto
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/JayChen123
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vinctchanx

repo_name: chenpage/chenpage.github.io
repo_url: https://github.com/chenpage/chenpage.github.io

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

nav:
  - 首页: index.md
  - 关于: about.md
  - python: 
    - python/abc.md 
    - python/aa.md
